[workspace]
resolver = "2"
members = ["crates/kanban-core", "crates/kanban-cli", "crates/kanban-tauri"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"
authors = ["akassharjun"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "deny"
unimplemented = "deny"

[workspace.dependencies]
rusqlite = { version = "0.31", features = ["bundled", "serde_json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1"
assert_cmd = "2"
insta = { version = "1", features = ["yaml", "filters"] }
proptest = "1"
tempfile = "3"

# new for kanban-tauri
tauri = { version = "2", features = [] }
tauri-build = { version = "2", features = [] }
tauri-specta = { version = "2.0.0-rc.21", features = ["derive", "typescript"] }
specta = { version = "2.0.0-rc.22", features = ["derive"] }
specta-typescript = "0.0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
tauri-plugin-shell = "2"
