// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command: list all projects.
 * 
 * # Errors
 * 
 * Returns an error if the workspace mutex is poisoned, the blocking task fails
 * to join, or the underlying query fails.
 */
async listProjects() : Promise<Result<ProjectDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get a single project by `prefix`.
 * 
 * # Errors
 * 
 * Returns `ApiError::NotFound` if no project has the given prefix, or an error
 * if the workspace mutex is poisoned, the blocking task fails to join, or the
 * underlying query fails.
 */
async getProject(prefix: string) : Promise<Result<ProjectDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { prefix }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list the issues of the project identified by `project` (its prefix).
 * 
 * # Errors
 * 
 * Returns an error if the workspace mutex is poisoned, the blocking task fails
 * to join, or the underlying query fails.
 */
async listIssues(project: string) : Promise<Result<IssueDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_issues", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get a single issue by its `key` (identifier, e.g. `AUTH-12`).
 * 
 * # Errors
 * 
 * Returns `ApiError::NotFound` if no issue has the given identifier, or an
 * error if the workspace mutex is poisoned, the blocking task fails to join, or
 * the underlying query fails.
 */
async getIssue(key: string) : Promise<Result<IssueDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_issue", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list the statuses of the project identified by `project` (its prefix).
 * 
 * # Errors
 * 
 * Returns an error if the workspace mutex is poisoned, the blocking task fails
 * to join, or the underlying query fails.
 */
async listStatuses(project: string) : Promise<Result<StatusDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_statuses", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list the labels of the project identified by `project` (its prefix).
 * 
 * # Errors
 * 
 * Returns an error if the workspace mutex is poisoned, the blocking task fails
 * to join, or the underlying query fails.
 */
async listLabels(project: string) : Promise<Result<LabelDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_labels", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: read the GUI settings.
 * 
 * # Errors
 * Returns an error if the mutex is poisoned, the task fails to join, or the read fails.
 */
async getSettings() : Promise<Result<Settings, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: persist the theme choice.
 * 
 * # Errors
 * Returns an error if the mutex is poisoned, the task fails to join, or the write fails.
 */
async updateSettings(theme: ThemeChoice) : Promise<Result<Settings, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: apply an operation (the single domain mutator).
 * 
 * The operation is received as JSON and deserialized into `Operation`; the
 * frontend's `ops.ts` builders construct the correct shape (Operation is not
 * part of the generated bindings because it is not a specta `Type`).
 * 
 * # Errors
 * Returns `ApiError::Validation` if the JSON is not a valid operation, or an
 * error if the mutex is poisoned, the task fails to join, or the write fails.
 */
async apply(op: JsonValue) : Promise<Result<ApplyResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply", { op }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: undo the most recent operation.
 * # Errors
 * Returns an error if there is nothing to undo, the mutex is poisoned, the task fails to join, or the write fails.
 */
async undo() : Promise<Result<ApplyResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: redo the most recently undone operation.
 * # Errors
 * Returns an error if there is nothing to redo, the mutex is poisoned, the task fails to join, or the write fails.
 */
async redo() : Promise<Result<ApplyResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Errors returned by Tauri command handlers to the frontend.
 */
export type ApiError = 
/**
 * The requested resource was not found.
 */
{ kind: "NotFound"; resource: string; key: string } | 
/**
 * A field failed validation.
 */
{ kind: "Validation"; field: string; message: string } | 
/**
 * The operation conflicts with existing state.
 */
{ kind: "Conflict"; message: string } | 
/**
 * An internal error occurred.
 */
{ kind: "Internal"; message: string }
/**
 * Result of applying an operation: the new `operation_log` row id.
 */
export type ApplyResult = { op_id: number }
export type IssueDto = { id: string; project_id: string; seq: number; identifier: string; title: string; description: string | null; status_id: string; priority: string; due_date: string | null; sort_key: number; created_at: string; updated_at: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LabelDto = { id: string; project_id: string; name: string; color: string }
export type ProjectDto = { id: string; name: string; prefix: string; description: string | null; icon: string | null; status: string; created_at: string; updated_at: string }
/**
 * App-level settings surfaced to the GUI.
 */
export type Settings = { theme: ThemeChoice }
export type StatusDto = { id: string; project_id: string; name: string; category: string; color: string; position: number }
/**
 * The user's theme preference.
 */
export type ThemeChoice = "system" | "light" | "dark"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
